### ISSUE TITLE
theres issue while running the data_clean = pd.DataFrame(scl.fit_transform(Final_data[fields]), columns = fields)

### ISSUE THREAD

**Issue by sushmitacse** [harishpuvvada/LoanDefault-Prediction#3]

**Comment by sushmitacse** [comment]
it gives ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by harishpuvvada** [comment]
It must be because of different versions of packages. This must solve it.
https://stackoverflow.com/questions/31323499/sklearn-error-valueerror-input-contains-nan-infinity-or-a-value-too-large-for
